const routeConstants = {
  ROOT: "/",
  HOME: "/",
  SHOP: "/shop",
  PRODUCT_DETAILS: "/product/details",
  TRACK_ORDER: "/track_order",
  TRACK_ORDER_DETAILS: "/track_order/details",
  COMPARE: "/compare",
  WISHLIST: "/wishlist",
  CHECKOUT: "/checkout",
  CHECKOUT_SUCCESS: "/checkout/success",
  CART: "/cart",
  SIGN: "/sign",
  FORGOT_PASSWORD: "/forgot_pwd",
  RESET_PASSWORD: "/reset_pwd",
  MAIL_VERIFY: "/mail_verify",
  FAQ: "/faq",
  ABOUT: "/about",
  SUPPORT: "/support",
  BLOG: "/blog",
  BLOG_DETAIL: "/blog/details",
  PAGE_NOT_FOUND: "/*",
};

export default routeConstants;
